apiVersion: v1
kind: ConfigMap
metadata:
  name: ${APP_NAME}-config
  namespace: ${NAMESPACE}
data:
  AUTH_URL: "${AUTH_URL}"
  POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
  POSTGRES_HOST: "postgres-service.${POSTGRES_NAMESPACE}.svc.cluster.local"
  POSTGRES_PORT: "${POSTGRES_PORT}"
