apiVersion: v1
kind: Secret
metadata:
  name: ${APP_NAME}-secret
  namespace: ${NAMESPACE}
stringData:
  AUTH_SECRET: "${AUTH_SECRET}"
  POSTGRES_USERNAME: "${POSTGRES_USERNAME}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
