apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-website-deployment
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-website-deployment
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-website-deployment
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image.repository }}-website:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.app.name }}-config
            - secretRef:
                name: {{ .Values.app.name }}-secret
