replicaCount: 2
image:
  repository: nginx
  tag: "1.21"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

configMap:
  data:
    APP_ENV: production
    API_URL: "http://api.example.com"